name: mvp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.13.4
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  tflite_v2: ^1.0.0

  
  flutter:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.1.1
  image: ^4.1.3
  path_provider: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

